LOCAL_PUTTY_DIR = "C:\Program Files\PuTTY"
SANDBOX_IP = "192.170.1.2"
SANDBOX_USERNAME = "analyst"
SANDBOX_PASSWORD = "armada71"
SANDBOX_DEBUGGING_FOLDER = "C:\ida_windbg_temp"
SANDBOX_RUNDLL_PATH = "C:\windows\system32\\rundll32.exe"
